version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install -g typescript
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo 'Contents of dist directory:'
      - ls -R dist
      - echo 'Contents of package.json directory:'
      - ls -R package.json

artifacts:
  files:
    - package.json
    - package-lock.json
    - 'dist/**/*'
  discard-paths: yes
